;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sexp
        backward-sexp
        beginning-of-line-or-indentation
        cua-clear-rectangle-mark
        cua-cut-region
        cua-delete-region
        cua-paste
        dabbrev-expand
        eval-last-sexp
        evil-backward-char
        evil-backward-word-begin
        evil-delete
        evil-delete-char
        evil-delete-line
        evil-end-of-line
        evil-exit-visual-state
        evil-force-normal-state
        evil-forward-char
        evil-inner-single-quote
        evil-insert
        evil-insert-line
        evil-next-line
        evil-normal-state
        evil-paste-before
        evil-previous-line
        evil-visual-char
        kill-sexp
        open-line-below
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-yank
        paredit-backward
        paredit-backward-kill-word
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-join-sexps
        paredit-kill
        paredit-raise-sexp
        paredit-reindent-defun
        paredit-wrap-round
        slime-autodoc-space
        slime-space
        ))

(setq mc/cmds-to-run-once
      '(
        cua-set-rectangle-mark
        evil-goto-mark
        transpose-frame
        ))
