(source gnu)
(source melpa)

(depends-on "avy")
(depends-on "arduino-mode")
(depends-on "buffer-move")
(depends-on "c-eldoc")
(depends-on "elisp-slime-nav")
(depends-on "expand-region")
(depends-on "feature-mode")
(depends-on "goto-chg")
(depends-on "ido-ubiquitous")
(depends-on "ido-at-point")
(depends-on "ido-vertical-mode")
(depends-on "jump-char")
(depends-on "list-register")
(depends-on "magit")
(depends-on "monky")
(depends-on "multiple-cursors")
(depends-on "paredit")
(depends-on "projectile")
(depends-on "quack")
(depends-on "smart-tab")
(depends-on "smart-window")
(depends-on "smex")
(depends-on "undo-tree")
(depends-on "vimrc-mode")
(depends-on "window-number")
(depends-on "wrap-region")
(depends-on "xcscope")
(depends-on "yasnippet")
(depends-on "transpose-mark")
(depends-on "markdown-mode")
(depends-on "monokai-theme")
(depends-on "keyswap")


(development
 (depends-on "ecukes")
 (depends-on "espuds")
 (depends-on "macrostep"))
