* To Document:
Make a note of all the keybindings I've set up.
Write down all the customisation I might have to change depending on machine
    (e.g. python shell type)

* To Fix:
Figure out why python-mode's inbuilt flymake settings aren't working.
Slime -- when stepping through functions, buffers move around.

* Things to Do
** Monky kill hunk
There are many things in magit missing in monky, one of the more useful things
is the ability to kill a single hunk in the diff.

It might be as simple as calling "patch -R" ith the selected hunk, then
reverting the buffer to add this functionality.
** Org mode templates
Add org-capture template for work things
** repeat-last-command blacklist
I like the `repeat-last-command' keybindings, but there's just too many commands
in emacs, so the last command is generally a useless one, usually a motion
command bound to just as conventiant a keybinding.

There may be something with last-repeatable-command that I can do.
* Things to learn:
IBuffer
Dired
[[info:org#Capture%20-%20Refile%20-%20Archive][Continue reading Org manual]]
[[info:calc][Read about the calc package.]]
Learn about the simple emacs spreadsheet
EDE (hopefully help with Makefiles)
Semantic (another CEDET tool)
Learn all about navigating info files.

* I want:
1) Evil surround - deleting surroundings removes everything inside and to
   + the left of the cursor with it.
2) Shortcut to switch to magit in current window.
   find if a magit buffer exists, then
   (switch-to-buffer " ... ")
   + temporarily set same-window-regexps?
3) Search google/youtube/github for thing under point

* Check out:
** Stephs emacs config
*** cjp-library
+ [[file:stephs_emacs/lisp/cjp-library.el::228][Find double words]]
+ [[file:stephs_emacs/lisp/cjp-library.el::305][wc (count number of words in region)]]
+ [[file:stephs_emacs/lisp/cjp-library.el::351][Capitalize title.]]
*** Packages to check out
**** flymake cursor
Puts the error message in the minibuffer when point is on an error
Apparently usually have to mouse over.
Must check if that's built in by now.
**** pydoc info
Browse python documentation in info buffers
**** Sunrise Commander
Midnight commander clone inside emacs.
* Plugins:
** Plugins to check out:
+ hydra          :: Equivalent to submode in vim
** Code Folding.
+ folding      :: Must be automatic for code.
     Own version.
                  Should make my own version of code folding.
                  Have set of functions to fold/unfold in both
                  hs-minor-mode and outline-mode.
                  Want version to automatically make clone buffers to
                  allow for differently folded code in different
                  buffers.
                  Add the ability to fold on markers (for hiding
                     passwords in my password files)
     hs-minor-mode
                  Has hide and show
                  Doesn't have motion by folds
                  Commands built in to evil
                  Works nicely for more lancuaces than outline mode
     fold-dwim
                  "Unified interface to folding modes"
                  Same interface to outline, hs and folding
                  I already have a home-grown version that fits my
                    preferences more.
     global-semantic-folding-mode
                  apparently in cedet
     outline-minor-mode
                  Seems to do the same as hs-minor-mode
                  Adds in navigation commands
                  Have no idea why both these modes are in emacs.
                  Doesn't work well with C
* Evil
** Work out all the submodes.
Start with setting 'j' and 'k' to do what 'n' and 'p' currently do, then figure
out everything else when it bothers me.
*** Magit
*** Dired
*** Ibuffer
** Things that don't work
*** C-w C-] mapping
Make this mapping work by default in evil.
Use find-tag-other-window function
*** Make the 'vert' modifier work
Currently the 'vert' modifier isn't recognised, I want it.
*** C-6 / C-^ use count like vim
My implementation of C-6 / C-^ doesn't account for a given count in the same way
    as vim
    If given a count, should load that buffer number.
*** Start and end paragraph marks.
The '{ and '} marks in Ex commands for start and end of paragraph.
*** C-w c  (and similar) count like vim
The CTRL-W c command doesn't take a count, and I assume others don't either.
*** Vim 'formatoptions' equivalent with 'o' key
'o' when in a comment doesn't keep the comment.
*** History mappings g+ and g-
g+ and g-  aren't implemented
*** :windo :bufdo and :argdo
:windo  --  use walk-windows, but have to make it accept an :ex command
Maybe the idea of the other two commands is hard to port
** Make <ESC> exit helm
** Work out all the submodes.
Start with setting 'j' and 'k' to do what 'n' and 'p' currently do, then figure
out everything else when it bothers me.

Main thing I want in quite a lot of modes, is to keep SPC as leader bindings,
keep C-w and g\d window motion bindings, and the scrolling maps, but lose
everything else.

This is mostly as many modes have mappings for 'l' 'r' 'n' 'TAB' and others, and
I don't really care about those at the moment.
*** Remap all the convention maps
There are quite a few conventions in the different special mode buffers, many
are shared, many not.
Whenever there are shared mappings, make sure to make them shared in evil.
Make this file where these are all stored.

g -- refresh --> C-l
r -- older   --> o
l -- newer   --> i
n -- down    --> j
p -- up      --> k
**** Magit
**** Dired
**** Ibuffer
**** Help
**** Info
**** Man
Remove as much as possible to keep the original mappings
