* To Document:
  Make a note of all the keybindings I've set up.

* To Fix:
  Figure out why flymake in python-mode isn't doing anything

* I want:
  1) Grep all files in a fileset nicely (into *grep* buffer)
  2) Filter grep and occur lists.
  3) GrepAdd equivalent.
     + append-to-buffer
  4) Evil surround - deleting surroundings removes everything inside and to
     + the left of the cursor with it.
  5) Shortcut to switch to magit in current window.
     + temporarily set same-window-regexps?
  6) Save window configuration for each elscreen tab along with nameses-save
  7) Look through the options in Emacs Sessions
  8) Make each namesession create a temporary fileset so I can run commands on it
  9) Search google/youtube/github for thing under point
  10) [[http://www.emacswiki.org/emacs/ElscreenSeparateBufferLists][Tabs that I can associate buffers to.]]
  11) Different theme on terminal to window systems - remember server mode.
  12) Open multiple help files at the same time.
      + C-u C-h to invoke
      + rename-uniquely

* Check out:
** Stephs emacs config
*** cjp-library
    + [[file:stephs_emacs/lisp/cjp-library.el::12][Create a window setup function]]
    + [[file:stephs_emacs/lisp/cjp-library.el::228][Find double words]]
    + [[file:stephs_emacs/lisp/cjp-library.el::305][wc (count number of words in region)]]
    + [[file:stephs_emacs/lisp/cjp-library.el::351][Capitalize title.]]

* Things to learn:
  [[info:org#Column%20view][Continue reading Org manual]]
  Learn all about navigating info files.
  EDE (hopefully help with Makefiles)
  How to set prefix keys, especially in evil.

* Plugins:
** Plugins to check out:
       + el-get       :: an "extra" package manager for emacs packages.
       + ecb          :: emacs code browser
       + dired+       :: Extra functions for dired
       + direx        :: Tree viewer - can be used for viewing tree of code
       + projectile   :: treats files in git/mercurial repos as seperate
       + helm         :: fuzzy file finder and more.
       + icicles      :: has the buffer grep I want and much more

** Plugins to look for:
       + folding      :: Need this quite badly.

* Evil mode:
** Next
   Visual mode indentation keeping the visual selection.
   Find out the benefit of evil-define-command
   Possibly change the evil-unimpaired-newline functions to use it

** Map paredit mappings into evil normal mode.
   Though not sure it's possible with the <( and >) mappings
   i.e.
        W   - Move sexp
        B   - Move sexp
        gE  - Move sexp
        E   - Move sexp
        w   - Move WORD
        b   - Move WORD
        e   - Move WORD
        ge  - Move WORD

** Porting my vimrc
   Port unimpaired (or at least the part I use often)
   Get submodes (like submode.vim)
        evil-define-state
        (info "(evil) States")

** Keys that I feel comfortable replacing in evil, not going to in vim:
   Q
   gQ
   spelling commands.

** Things not in evil that are in vim:
   C-x C-(anything not linewise)
   [I, ]I, [D, ]D, [d, ]d, [i, ]i
   gp, gP
