* To Document:
  Make a note of all the keybindings I've set up.
  Write down all the customisation I might have to change
      (e.g. python shell type)

* To Fix:
  Figure out why python-mode's inbuilt flymake settings aren't working.

* Things to learn:
  [[info:org#Capture%20-%20Refile%20-%20Archive][Continue reading Org manual]]
  [[info:calc][Read about the calc package.]]
  EDE (hopefully help with Makefiles)
  Semantic (another CEDET tool)
  Learn all about navigating info files.

* I want:
  1) Filter grep and occur lists.
  2) GrepAdd equivalent.
     + append-to-buffer
  3) Evil surround - deleting surroundings removes everything inside and to
     + the left of the cursor with it.
  4) Shortcut to switch to magit in current window.
     find if a magit buffer exists, then
     (switch-to-buffer " ... ")
     + temporarily set same-window-regexps?
  5) Save window configuration for each elscreen tab along with nameses-save
  6) Look through the options in Emacs Sessions
  7) Make each namesession create a temporary fileset so I can run commands on it
  8) Search google/youtube/github for thing under point
  9) Automatic indirect buffers for folding.
  10) Open multiple help files at the same time.
      + C-u C-h to invoke
      + rename-uniquely

* Check out:
** Stephs emacs config

*** cjp-library
    + [[file:stephs_emacs/lisp/cjp-library.el::12][Create a window setup function]]
    + [[file:stephs_emacs/lisp/cjp-library.el::228][Find double words]]
    + [[file:stephs_emacs/lisp/cjp-library.el::305][wc (count number of words in region)]]
    + [[file:stephs_emacs/lisp/cjp-library.el::351][Capitalize title.]]

*** Packages to check out

**** flymake cursor
     Puts the error message in the minibuffer when point is on an error
     Apparently usually have to mouse over.
     Must check if that's built in by now.

**** pydoc info
     Browse python documentation in info buffers

**** Sunrise Commander
     Midnight commander clone inside emacs.

* Plugins:
** Plugins to check out:
       + ecb          :: emacs code browser
       + el-get       :: an "extra" package manager for emacs packages.
       + dired+       :: Extra functions for dired
       + direx        :: Tree viewer - can be used for viewing tree of code

** Plugins to look for:
       + folding      :: Must be automatic for code.
            hs-minor-mode
                         Has hide and show
                         Doesn't have motion by folds
                         Commands built in to evil
                         Works nicely for more lancuaces than outline mode
            fold-dwim
                         "Unified interface to folding modes"
                         Same interface to outline, hs and folding
            global-semantic-folding-mode
                         apparently in cedet
                         I can't find it.
            outline-minor-mode
                         Seems to do the same as hs-minor-mode
                         Adds in navigation commands
                         Have no idea why both these modes are in emacs.
                         Doesn't work well with C

* Evil mode:
** Next
   Find out the benefit of evil-define-command
   Read this [[http://zuttobenkyou.wordpress.com/2011/02/15/some-thoughts-on-emacs-and-vim/][blog post]] for some ideas.

** Map paredit mappings into evil normal mode.
   The functions that start at the end of an sexp don't work well due to the
   paint of the cursor being one off that in emacs.
   Though not sure it's possible with the <( and >) mappings
   i.e.
        W   - Move sexp
        B   - Move sexp
        gE  - Move sexp
        E   - Move sexp
        w   - Move WORD
        b   - Move WORD
        e   - Move WORD
        ge  - Move WORD

** Porting my vimrc
   Get submodes (like submode.vim)
        evil-define-state
        (info "(evil) States")

** Things not in evil that are in vim:
   C-x C-(anything not linewise)
   [I, ]I, [D, ]D, [d, ]d, [i, ]i
   gp, gP
