* To Document:
Make a note of all the keybindings I've set up.
Write down all the customisation I might have to change depending on machine
    (e.g. python shell type)

* To Fix:
Figure out why python-mode's inbuilt flymake settings aren't working.
Slime -- when stepping through functions, buffers move around.

* Things to Do
** Monky kill hunk
** TODO Minibuffer eval and toggle-shifted-keys
Because the minibuffer eval hook is run every time the minibuffer is opened, but
the keymap is kept the same between instances, toggling the keybindings in the
minibuffer hook means each time the minibuffer is used the keybindings are
different.
I either need to change the keybindings directly in the minibuffer keymap, or
find a different hook that's only used on the initial startup.
There are many things in magit missing in monky, one of the more useful things
is the ability to kill a single hunk in the diff.

It might be as simple as calling "patch -R" ith the selected hunk, then
reverting the buffer to add this functionality.
** Org mode templates
Add org-capture template for work things
** repeat-last-command blacklist
I like the `repeat-last-command' keybindings, but there's just too many commands
in emacs, so the last command is generally a useless one, usually a motion
command bound to just as conventiant a keybinding.

There may be something with last-repeatable-command that I can do.
* Things to learn:
IBuffer
Dired
[[info:org#Capture%20-%20Refile%20-%20Archive][Continue reading Org manual]]
[[info:calc][Read about the calc package.]]
Learn about the simple emacs spreadsheet
EDE (hopefully help with Makefiles)
Semantic (another CEDET tool)
Learn all about navigating info files.

* I want:
1) Evil surround - deleting surroundings removes everything inside and to
   + the left of the cursor with it.
2) Shortcut to switch to magit in current window.
   find if a magit buffer exists, then
   (switch-to-buffer " ... ")
   + temporarily set same-window-regexps?
3) Search google/youtube/github for thing under point

* Check out:
** Stephs emacs config
*** cjp-library
+ [[file:stephs_emacs/lisp/cjp-library.el::228][Find double words]]
+ [[file:stephs_emacs/lisp/cjp-library.el::305][wc (count number of words in region)]]
+ [[file:stephs_emacs/lisp/cjp-library.el::351][Capitalize title.]]
*** Packages to check out
**** flymake cursor
Puts the error message in the minibuffer when point is on an error
Apparently usually have to mouse over.
Must check if that's built in by now.
**** pydoc info
Browse python documentation in info buffers
**** Sunrise Commander
Midnight commander clone inside emacs.
* Plugins:
** Plugins to check out:
+ hydra          :: Equivalent to submode in vim
** Code Folding.
+ folding      :: Must be automatic for code.
     Own version.
                  Should make my own version of code folding.
                  Have set of functions to fold/unfold in both
                  hs-minor-mode and outline-mode.
                  Want version to automatically make clone buffers to
                  allow for differently folded code in different
                  buffers.
                  Add the ability to fold on markers (for hiding
                     passwords in my password files)
     hs-minor-mode
                  Has hide and show
                  Doesn't have motion by folds
                  Commands built in to evil
                  Works nicely for more lancuaces than outline mode
     fold-dwim
                  "Unified interface to folding modes"
                  Same interface to outline, hs and folding
                  I already have a home-grown version that fits my
                    preferences more.
     global-semantic-folding-mode
                  apparently in cedet
     outline-minor-mode
                  Seems to do the same as hs-minor-mode
                  Adds in navigation commands
                  Have no idea why both these modes are in emacs.
                  Doesn't work well with C
